version: '3.8'

services:
  auth:
    build: .
    container_name: auth
    environment: 
      - ACCESS_SECRET=banana
      - REFRESH_SECRET=banana
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:8084/auth
      - GITHUB_API_URL=http://fake_server:8081
      - GITHUB_BASE_URL=http://fake_server:8081
      - GITHUB_CLIENT_ID=abcdef123456
      - GITHUB_CLIENT_SECRET=banana
      - WEB_DOMAIN=localhost
      - WEB_URL=http://localhost:3000
    ports: 
      - 8080:8080
  
  auth_tests:
    build: tests/container_tests
    container_name: auth_tests
    depends_on: 
      - auth
    environment: 
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:8084/auth
  
  fake_server:
    build: tests/fake_server
    container_name: fake_server