sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d

script:
  - docker exec -it client npm run ci-test
  - docker exec -it server_test npm run ci-test

after_script:
  - docker exec -it client npm run coverage
  - docker exec -it server_test npm run coverage
  - docker-compose down

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t wahuh/slothy.io-client ./client
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t wahuh/slothy.io-server ./server
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push wahuh/slothy.io-client
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push wahuh/slothy.io-server
branches:
  only:
    - master
    - development

notifications:
  webhooks: https://coveralls.io/webhook
