sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d

script:
  - docker exec -it client npm run ci-test
  - docker exec -it server_test npm run ci-test
  - docker exec -it client npm run coverage
  - docker exec -it server_test npm run coverage

after_script:
  - docker-compose down

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t wahuh/slothy.io-server ./server
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push wahuh/slothy.io-server
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker exec -it client npm run build
branches:
  only:
    - master
    - development

deploy:
  - provider: elasticbeanstalk
    region: eu-west-1
    app: slothy.io
    env: Slothyio-env
    bucket_name: elasticbeanstalk-eu-west-1-566169246547
    bucket_path: slothy.io
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
  - provider: script
    script: docker exec -it client npm run deploy
    on:
      branch: master

notifications:
  webhooks: https://coveralls.io/webhook
