sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d

script:
  - docker exec -it client npm run coverage
  - docker exec -it server_test npm run coverage

after_script:
  - docker-compose down

branches:
  only:
    - master
    - development
