sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build -d

script:
  - docker exec -it client npm run ci-test
  - docker exec -it server_test npm run ci-test

after_script:
  - docker exec -it client npm run coverage
  - docker exec -it server_test npm run coverage
  - docker-compose down

branches:
  only:
    - master
    - development

notifications:
  webhooks: https://coveralls.io/webhook