version: '3.8'

services:
  auth:
    container_name: auth
    volumes: 
      - ./services/auth:/node/app
    build:
      context: services/auth
    command: npm start
    labels: 
      - traefik.http.routers.auth.rule=Host(`api.localhost`) && Path(`/auth`)

  gateway:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command: 
      - --api.insecure=true
      - --providers.docker=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
