version: "3"
services:
  server:
    command: ["npm", "run", "dev"]

  server_tests:
    container_name: server_tests
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.test.env
    command: ["npm", "run", "test"]
