version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
  server:
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env