version: "3"
services:
  client:
    environment:
      - "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
      - "TRAVIS_JOB_ID=${TRAVIS_JOB_ID}"

  database_test:
    environment:
      - "POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${TEST_POSTGRES_DB}"
      - "POSTGRES_HOST=${TEST_POSTGRES_HOST}"
      - "POSTGRES_PORT=${TEST_POSTGRES_PORT}"
      - "POSTGRES_USER=${TEST_POSTGRES_USER}"
      - "JWT_SECRET=${TEST_JWT_SECRET}"

  server_test:
    environment:
      - "POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${TEST_POSTGRES_DB}"
      - "POSTGRES_HOST=${TEST_POSTGRES_HOST}"
      - "POSTGRES_PORT=${TEST_POSTGRES_PORT}"
      - "POSTGRES_USER=${TEST_POSTGRES_USER}"
      - "JWT_SECRET=${TEST_JWT_SECRET}"
      - "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
      - "TRAVIS_JOB_ID=${TRAVIS_JOB_ID}"
