version: "3"
services:
  database_dev:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.dev.env

  database_test:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.test.env

  server_dev:
    container_name: server_dev
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.dev.env
    command: ["npm", "run", "dev"]

  server_test:
    container_name: server_test
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.test.env
    command: ["tail", "-f", "/dev/null"]
