version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./client:/app
    command: ["npm", "start"]

  database_test:
    image: postgres:latest
    restart: always

  server_test:
    container_name: server_test
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    command: ["npm", "run", "test-stall"]
