version: "3.8"

services:
  email:
    container_name: email
    volumes:
      - ./services/email/src:/app
    build:
      context: services/email
    ports:
      - 8080:80
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
