version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env
  server:
    container_name: server
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env
  server_tests:
    container_name: server_tests
    build:
      dockerfile: test.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.test.env
