version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env

  server:
    container_name: server
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env
      
