version: '3.8'

# development environment for services
services: 
  auth:
    build: auth
    environment: 
      ACCESS_SECRET: banana
      REFRESH_SECRET: banana
      SECURE_COOKIES: 0
      WEB_DOMAIN: localhost
      WEB_URL: http://localhost:3000
    env_file: 
      # should contain GITHUB_API_URL, GITHUB_BASE_URL, GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET
      - auth/.env